### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by TCOTC** [syh19/siyuan-plugin-task-list#13]
不是在使用插件，而是正常编辑文档的过程中输出的报错：

![image](https://github.com/syh19/siyuan-plugin-task-list/assets/78434827/59a8b894-6779-4f2d-afaa-7ce46b9e8d7e)

```
plugin:siyuan-plugin-task-list:88 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at Zre (plugin:siyuan-plugin-task-list:88:299254)
    at Comment.eval (plugin:siyuan-plugin-task-list:88:300119)
    at Hy.emit (main.744a14c4fe28136d2754.js:781:4825)
    at main.744a14c4fe28136d2754.js:6550:1175
    at Array.forEach (<anonymous>)
    at gt.msgCallback (main.744a14c4fe28136d2754.js:6550:1152)
    at a.onmessage (main.744a14c4fe28136d2754.js:9:9071)
Zre @ plugin:siyuan-plugin-task-list:88
eval @ plugin:siyuan-plugin-task-list:88
emit @ main.744a14c4fe28136d2754.js:781
（匿名） @ main.744a14c4fe28136d2754.js:6550
msgCallback @ main.744a14c4fe28136d2754.js:6550
a.onmessage @ main.744a14c4fe28136d2754.js:9
```

报错来源：

![image](https://github.com/syh19/siyuan-plugin-task-list/assets/78434827/d6652132-2fb9-43cd-b64d-2196f0b9ce8a)

**Comment by syh19** [comment]
@TCOTC 好的，感谢感谢，下个版本修复这个问题。

**Comment by syh19** [comment]
@TCOTC 这个问题在`v0.0.7`版本修复啦，我就先关了，如果还有问题的话麻烦再反馈一下，谢谢啦。
